In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Get the data

In [2]:
df= pd.read_csv('DiabetesClassification.csv')

## Explore and clean the data

In [3]:
df.head()

,Age,Gender,BMI,Blood Pressure,FBS,HbA1c,Family History of Diabetes,Smoking,Diet,feat1,Exercise,Diagnosis
0,45,male,25,Normal,100.0,5.7,no,No,Healthy,0.932037,Regular,No
1,55,Female,30,High,120.0,6.4,yes,Yes,Poor,0.673781,No,Yes
2,65,male,35,High,140.0,7.1,YES,Yes,Poor,0.220245,No,Yes
3,75,Female,40,High,160.0,7.8,Yes,Yes,Poor,NaN,No,Yes
4,40,Male,20,Normal,80.0,5.0,No,No,Healthy,NaN,Regular,No

In [4]:
df.describe()

              Age         BMI         FBS       HbA1c      feat1
count  128.000000  128.000000  127.000000  125.000000  12.000000
mean    42.031250   35.359375  163.149606    7.895200   0.686728
std     16.783915   14.981739   61.123097    2.130533   0.284487
min     12.000000   10.000000   80.000000    5.000000   0.053634
25%     28.000000   24.000000  120.000000    6.400000   0.644295
50%     40.000000   34.000000  160.000000    7.800000   0.776854
75%     55.000000   45.500000  210.000000    9.200000   0.899161
max     75.000000   67.000000  280.000000   12.000000   0.940305

In [5]:
df.shape

(128, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         128 non-null    int64
 1   Gender                      128 non-null    object
 2   BMI                         128 non-null    int64
 3   Blood Pressure              125 non-null    object
 4   FBS                         127 non-null    float64
 5   HbA1c                       125 non-null    float64
 6   Family History of Diabetes  128 non-null    object
 7   Smoking                     128 non-null    object
 8   Diet                        127 non-null    object
 9   feat1                       12 non-null     float64
 10  Exercise                    128 non-null    object
 11  Diagnosis                   128 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 12.1+ KB

## Check for null values

In [7]:
df.isna().sum()

Age                             0
Gender                          0
BMI                             0
Blood Pressure                  3
FBS                             1
HbA1c                           3
Family History of Diabetes      0
Smoking                         0
Diet                            1
feat1                         116
Exercise                        0
Diagnosis                       0
dtype: int64

In [8]:
df.isna().sum()/df.shape[0] *100

Age                            0.00000
Gender                         0.00000
BMI                            0.00000
Blood Pressure                 2.34375
FBS                            0.78125
HbA1c                          2.34375
Family History of Diabetes     0.00000
Smoking                        0.00000
Diet                           0.78125
feat1                         90.62500
Exercise                       0.00000
Diagnosis                      0.00000
dtype: float64

## Drop column with 90% null values

In [9]:
df=df.drop(columns=['feat1'])

In [10]:
df.head()

,Age,Gender,BMI,Blood Pressure,FBS,HbA1c,Family History of Diabetes,Smoking,Diet,Exercise,Diagnosis
0,45,male,25,Normal,100.0,5.7,no,No,Healthy,Regular,No
1,55,Female,30,High,120.0,6.4,yes,Yes,Poor,No,Yes
2,65,male,35,High,140.0,7.1,YES,Yes,Poor,No,Yes
3,75,Female,40,High,160.0,7.8,Yes,Yes,Poor,No,Yes
4,40,Male,20,Normal,80.0,5.0,No,No,Healthy,Regular,No

In [11]:
df.columns

Index(['Age', 'Gender', 'BMI', 'Blood Pressure', 'FBS', 'HbA1c',
       'Family History of Diabetes', 'Smoking', 'Diet', 'Exercise',
       'Diagnosis'],
      dtype='object')

In [12]:
df.columns= [col.lower().strip().replace(' ','_') for col in df.columns]

In [13]:
df.columns

Index(['age', 'gender', 'bmi', 'blood_pressure', 'fbs', 'hba1c',
       'family_history_of_diabetes', 'smoking', 'diet', 'exercise',
       'diagnosis'],
      dtype='object')

In [14]:
str_cols= df.select_dtypes(include='object').columns.tolist()

In [15]:
str_cols

['gender',
 'blood_pressure',
 'family_history_of_diabetes',
 'smoking',
 'diet',
 'exercise',
 'diagnosis']

In [16]:
for col in str_cols:
    df[col]=df[col].str.lower().str.strip()

In [17]:
df.head()

,age,gender,bmi,blood_pressure,fbs,hba1c,family_history_of_diabetes,smoking,diet,exercise,diagnosis
0,45,male,25,normal,100.0,5.7,no,no,healthy,regular,no
1,55,female,30,high,120.0,6.4,yes,yes,poor,no,yes
2,65,male,35,high,140.0,7.1,yes,yes,poor,no,yes
3,75,female,40,high,160.0,7.8,yes,yes,poor,no,yes
4,40,male,20,normal,80.0,5.0,no,no,healthy,regular,no

## checking for inconsitency in value in categorical columns

In [18]:
for col in str_cols:
    print(df[col].value_counts())

gender
male      68
female    58
femle      2
Name: count, dtype: int64
blood_pressure
high      77
normal    39
low        9
Name: count, dtype: int64
family_history_of_diabetes
no     77
yes    51
Name: count, dtype: int64
smoking
yes    79
no     49
Name: count, dtype: int64
diet
poor       79
healthy    48
Name: count, dtype: int64
exercise
no         79
regular    49
Name: count, dtype: int64
diagnosis
no     97
yes    31
Name: count, dtype: int64

In [19]:
df['gender']=df['gender'].replace({'femle':'female'})

In [20]:
df['gender'].value_counts()

gender
male      68
female    60
Name: count, dtype: int64

In [21]:
df.columns

Index(['age', 'gender', 'bmi', 'blood_pressure', 'fbs', 'hba1c',
       'family_history_of_diabetes', 'smoking', 'diet', 'exercise',
       'diagnosis'],
      dtype='object')

In [22]:
df['fbs']=df['fbs'].fillna(df['fbs'].median())

In [23]:
df['hba1c']=df['hba1c'].fillna(df['hba1c'].median())

In [24]:
df['blood_pressure']=df['blood_pressure'].fillna(df['blood_pressure'].mode()[0])
df['diet']=df['diet'].fillna(df['diet'].mode()[0])

In [25]:
df.isna().sum()

age                           0
gender                        0
bmi                           0
blood_pressure                0
fbs                           0
hba1c                         0
family_history_of_diabetes    0
smoking                       0
diet                          0
exercise                      0
diagnosis                     0
dtype: int64

In [26]:
str_cols.pop()

'diagnosis'

In [27]:
str_cols

['gender',
 'blood_pressure',
 'family_history_of_diabetes',
 'smoking',
 'diet',
 'exercise']

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
label_encoder=LabelEncoder()

In [30]:
for col in str_cols:
    df[col]=label_encoder.fit_transform(df[col])

In [31]:
df.head()

,age,gender,bmi,blood_pressure,fbs,hba1c,family_history_of_diabetes,smoking,diet,exercise,diagnosis
0,45,1,25,2,100.0,5.7,0,0,0,1,no
1,55,0,30,0,120.0,6.4,1,1,1,0,yes
2,65,1,35,0,140.0,7.1,1,1,1,0,yes
3,75,0,40,0,160.0,7.8,1,1,1,0,yes
4,40,1,20,2,80.0,5.0,0,0,0,1,no

In [32]:
from sklearn.model_selection import cross_val_score,KFold,GridSearchCV

In [34]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [35]:
X=df.drop(columns=['diagnosis'],axis=1)
y=df['diagnosis']

In [36]:
svc=SVC(kernel='sigmoid')

In [37]:
kf=KFold(n_splits=5,shuffle=True,random_state=42)
dt_scores=cross_val_score(svc,X,y,cv=kf)
dt_mean_scores=np.mean(dt_scores)

In [38]:
dt_mean_scores

np.float64(0.6175384615384616)

In [39]:
dt_scores

array([0.61538462, 0.57692308, 0.61538462, 0.64      , 0.64      ])

## Hyperparameter Tuning

In [43]:
model_param={
    'kernel':['linear','poly','rbf','sigmoid'],
    'C':[1.0,1.5,2.0],
    'tol':[0.003,0.002,0.001]
}

In [44]:
model_grid_search=GridSearchCV(svc,model_param,cv=kf,scoring='accuracy')
model_grid_search.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=SVC(kernel='sigmoid'),
             param_grid={'C': [1.0, 1.5, 2.0],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
                         'tol': [0.003, 0.002, 0.001]},
             scoring='accuracy')

In [45]:
model_grid_search.best_estimator_

SVC(kernel='linear', tol=0.003)

In [46]:
model_grid_search.best_params_

{'C': 1.0, 'kernel': 'linear', 'tol': 0.003}

In [47]:
model_grid_search.best_score_

np.float64(0.9763076923076923)

In [48]:
final_model= SVC(C=1.0,kernel='linear',tol=0.003)

In [50]:
final_model.fit(X,y)

SVC(kernel='linear', tol=0.003)

In [51]:
import joblib

In [52]:
joblib.dump(final_model,'final_model.pkl')

['final_model.pkl']